- name: Build iOS Action
  # You may pin to the exact commit or the version.
  # uses: sparkfabrik/ios-build-action@bf6e2875423bae3d2c7d487ba5622cba8a42075f
  uses: sparkfabrik/ios-build-action@v1.1.0
  with:
    # Project path
    project-path: 
    # Base64 encoded p12 key
    p12-key-base64: # optional
    # Base64 encoded certificate for the p12 key
    p12-cer-base64: # optional
    # Base64 encoded p12 file (key + cert)
    p12-base64: # optional
    # Base64 encoded mobileprovision file
    mobileprovision-base64: 
    # For example, iOS Distribution
    code-signing-identity: 
    # Team id
    team-id: 
    # Workspace path
    workspace-path: # optional, default is 
    # Choose app-store, ad-hoc, package, enterprise, development, or developer-id
    export-method: # optional, default is app-store
    # For example, Debug, Release
    configuration: # optional, default is Release
    # Certificate password
    certificate-password: # optional, default is 
    # Output path of ipa
    output-path: # optional, default is output.ipa
    # Scheme
    scheme: # optional, default is 
    # Targets to disable automatic code signing. Input targets separated by ,. For example, 'MyApp,YourApp'.
    disable-targets: # optional, default is 
    # Boolean to tell if `pod install` should be run during build.
    build-pods: # optional
    # The path to the Podfile.
    pods-path: # optional, default is Podfile
    # Boolean to tell the Action to upload the .ipa to Browserstack App Live after the build.
    browserstack-upload: # optional
    # Browserstack username (required if browserstack-upload == true)
    browserstack-username: # optional, default is 
    # Browserstack access key (required if browserstack-upload == true)
    browserstack-access-key: # optional, default is 
